### PR TITLE
Adding a get sync getItems method

### LINKED ISSUE #109: Add synchronous support to the DeliveryClient
### Motivation

After updating a large application to the latest version of the Java SDK, all calls to the DeliveryClient had to wrapped in a synchronous wrapper. It would be helpful if there were a built-in way to call the DeliveryClient synchronously rather than introducing additional code to the project.

### Proposed solution

Add alternate methods for working with the DeliveryClient synchronously, for example:

`deliveryClient.getItems().toSync()` or `deliveryClient.getItemsSynchronously()`

### Additional context

Here is the wrapper class that I had to write:

```
public class DeliveryClientHelper {
    public static <T> T toSync(CompletionStage<T> completionStage) {
        try {
            return completionStage.toCompletableFuture().get();
        } catch (InterruptedException e) {
            log.error("Error converting completion stage: {}", e.getMessage());
        } catch (ExecutionException e) {
            log.error("Error converting completion stage: {}", e.getMessage());
        }
        return null;
    }
}

```

An example call using the wrapper:

```
List<AgencySiteBlogLanding> blogHomepages = DeliveryClientHelper.toSync(deliveryClient.getItems(AgencySiteBlogLanding.class));
```

An ideal way to use the DeliveryClient

```
List<AgencySiteBlogLanding> blogHomepages = deliveryClient.getItems(AgencySiteBlogLanding.class).toSync();
```

### PR DESCRIPTION
**Pull request by cunhazera**
Fixes #109 

Commentary:
 - It would be little harder to have a `toSync` method, because I'd need to return an instance of `DeliveryClient` so the items should be stored in a field, so then I could have an `deliveryClient.getItems(Class.class).toSync()`. If I did this, the `DeliveryClient` class would need a generic type at the class level, so that would break a lot of old code. Anyway, if anyone has a better idea we can talk about, to have a `toSync` method.

### CODE REVIEW

**Comment by Simply007** [comment]
This pull request only covers only the getItems method, but there is a bunch of remaining in the delivery client (i.e. getTypes).

I would like to avoid doubling the method count in the delivery client. I would appreciate a unified approach.
It might be possible to inherit from CompletionStage and extend it with a method called `toSync`. This would not break any compatibility, because of inheritance and it would allow having nice and fluent syntax as described in https://github.com/Kentico/kontent-java-packages/issues/109#issuecomment-702618081.

According to the tests, I would like to not have current tests modified and just add new ones, because the functionality is also just added, not modified.

Mind the Readme - there should be the mention of the functionality too.

**Review by Simply007 — CHANGES_REQUESTED** [review]
https://github.com/Kentico/kontent-java-packages/pull/112#issuecomment-704091150

**Review by makma — APPROVED** [review]

**Comment by Simply007** [comment]
@cunhazera - do you have any update on this?

**Comment by Simply007** [comment]
Hi!

This pull request has gone quiet. 👻
It’s been a while since the last update here.

If we missed anything on this issue or if you want to keep it open, feel free to do so.

Thanks for being a part of the Kentico community!

**Pull request closed without merging**
