### PR TITLE
add @JsonIgnore to Element.parent

### PR DESCRIPTION
**Pull request by connyduck**
### Motivation

This makes it possible to serialize ContentItems with Jackson again (it breaks the circular reference chain). It helps with our custom caching solution.

### Checklist

- [x] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [x] Tests are passing
- [ ] Docs have been updated (if applicable)
- [x] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

If manual testing is required, what are the steps?

### CODE REVIEW

**Comment by Simply007** [comment]
hello @connyduck ,

I will take a look at it hopefully this week (mainly the consequences of the decorator). Could you describe what is your core issue?

Ideally, if you can add a test for this functionality - something like there is a JSON response from Kontent and I need to deserialize it to the model X and serialize it back.

**Comment by connyduck** [comment]
I added a test that crashes with `Infinite recursion (StackOverflowError)` without the annotation.

**Review by Simply007 — APPROVED** [review]
Looks cool, it seems there are no unexpected consequences of adding the decorator for parent property. 

Thanks for the test!

Note for feature reference: Lombok equals implementation is taking care of property equality check for the new test.

**Comment by Simply007** [comment]
@connyduck - thanks for the pull request - it should be released in [v4.3.1](https://github.com/Kentico/kontent-java-packages/releases/tag/4.3.1).

**Pull request merged**
