### PR TITLE
add support for custom elements

### LINKED ISSUE #77: Custom element support
### Motivation

In the upcoming days/weeks there will be new element type (custom element) in the Delivery output.
This will cause the failure of model binding since it's not included in the known type ids.
`known type ids = [Element, asset, date_time, modular_content, multiple_choice, number, rich_text, taxonomy, text, url_slug]`

`com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'custom' into a subtype of [simple type, class com.kenticocloud.delivery.Element]: known type ids = [Element, asset, date_time, modular_content, multiple_choice, number, rich_text, taxonomy, text, url_slug]
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.kenticocloud.delivery.ContentItemResponse["item"]->com.kenticocloud.delivery.ContentItem["elements"]->java.util.LinkedHashMap["ahojky"])
	at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:42)
	at com.fasterxml.jackson.databind.DeserializationContext.unknownTypeIdException(DeserializationContext.java:1477)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownTypeId(DeserializationContext.java:1170)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._handleUnknownTypeId(TypeDeserializerBase.java:282)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:156)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:112)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:209)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:519)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:362)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:104)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:104)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3786)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2115)
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2612)
	at com.kenticocloud.delivery.AsyncDeliveryClient.putInCache(AsyncDeliveryClient.java:469)
	at com.kenticocloud.delivery.AsyncDeliveryClient.lambda$executeRequest$12(AsyncDeliveryClient.java:388)
	at `

It should be supported in generator as well.

### Proposed solution

Add custom element into `known type ids` and ensure the binding won't fail in the future when new element type is added.

For generator add new case and handling in 

> public JavaFile generateSource(ContentType type)

### Additional context

Expected Delivery output:

>
.
.
.
"elements": {
.
.
.
  "title": {
    "type": "text",
    "name": "Title",
    "value": "Shiny Globe"
  },
   .
   .
   .
  **"colorPicker": {
    "type": "custom_field",
    "name": "Color_Picker",
    "value": "#4286f4"
   },**
    .
    .
    .
.
.
.

### PR DESCRIPTION
**Pull request by connyduck**
### Motivation

Fixes #77

### Checklist

- [x] Code follows coding conventions held in this repo
- [x] Automated tests have been added
- [x] Tests are passing
- [x] Docs have been updated (if applicable)
- [x] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### CODE REVIEW

**Comment by Simply007** [comment]
Hello @connyduck!

Thanks for your contribution! I will try my best to check the pull request this week.

BTW: May I ask how did you find this issue? Are you working with Kentico Kontent and Android?

**Comment by connyduck** [comment]
We use the kontent delivery library in our Spring Boot backend and we have custom elements in our project.

**Review by Simply007 — COMMENTED** [review]
Notes:
* Readme - describe how the custom elements should be loaded
    * I might add something like `GetCustomElement`, or edit [GetString](https://github.com/Kentico/kontent-java-packages/blob/d08e911fc824993ac47c1c71639311048bf0b192/kontent-delivery/src/main/java/kentico/kontent/delivery/ContentItem.java#L92)) - what do you think?
        * There could be also [this test extended](https://github.com/Kentico/kontent-java-packages/blob/master/kontent-delivery/src/test/java/kentico/kontent/delivery/JacksonBindingsTest.java#L83)
* Support for model generator: extend generator for [Custom element property](https://github.com/Kentico/kontent-java-packages/blob/master/kontent-delivery-generators/src/main/java/kentico/kontent/delivery/generators/CodeGenerator.java#L95)
    * Extend [tests](https://github.com/Kentico/kontent-java-packages/blob/master/kontent-delivery-generators/src/test/java/kentico/kontent/delivery/generators/CodeGeneratorTest.java#L26): It would be great to test the output of the class (ideally syntactically, but string comparison is ok as well).

**Comment by Simply007** [comment]
@connyduck - are you willing to take a look at some notes I have noted above? I am willing to take a look at it and finish the feature, but I can't promise you a fixed date.

Your changes look OK and I am willing to merge the pull request and keep the issue open with the notes I have added above.

**Comment by connyduck** [comment]
@Simply007 I think I addressed everything 
Not sure why the CI is failing though

**Comment by Simply007** [comment]
Let me check the CI.

**Comment by Simply007** [comment]
I have removed the unused step that was failing (I am currently using a different approach to publish the versions).

I will take a look at the changes - but from my brief check, the changes look awesome @connyduck!
Thanks for that :) 

Is there any specific date you would like to have the functionality out? 🙂

**Comment by connyduck** [comment]
Thanks! 

> Is there any specific date you would like to have the functionality out? 🙂

No, but the sooner, the better of course!

**Review by Simply007 — APPROVED** [review]
I have gone through the code and everything looks great.
Extra thanks for extending tests for the model generator!

I will merge it tomorrow and publish a new feature version.

**Comment by Simply007** [comment]
Released in [v4.3.0](https://bintray.com/kentico/kontent-java-packages/kontent-delivery/4.3.0).
Thanks, @connyduck - one of the smoothest cooperation lately.

I am about to mention this pull request in the upcoming [Kentico Developer Flash](https://github.com/Kentico/Home/discussions?discussions_q=category%3A%22Developer+Flash%22)!

**Pull request merged**
